version: "3.8"

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster-1234
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Partition-related configurations
      - KAFKA_CFG_NUM_PARTITIONS=2                   # Default number of partitions for auto-created topics
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1       # Default replication factor
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true     # Enable auto creation of topics
      - KAFKA_CFG_OFFSETS_TOPIC_NUM_PARTITIONS=2     # Number of partitions for the offsets topic
      - KAFKA_CFG_TRANSACTION_STATE_LOG_NUM_PARTITIONS=2 # Number of partitions for the transaction topic
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1    # Minimum in-sync replicas for transaction log
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  kafka_data:
